In [25]:
import pandas as pd
import numpy as np
import joblib

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [26]:
data = pd.read_csv("../data/query.csv")

X = data["query"]
y = data["intent"]

In [27]:
data.sample(5)

                                                 query                intent
408  request to remove umc case imposed on me durin...   Security_and_Safety
431  company interview schedule not visible on plac...            Placements
179                       Immigration support contact?  International_Affair
106                         Discipline issue on campus   Security_and_Safety
101                        Complaint about eve teasing   Security_and_Safety

In [28]:
data.shape

(558, 2)

In [29]:
print(data['intent'].value_counts())

intent
Residential_Services                    69
Examination                             67
Academics                               67
Division_of_Research_and_Development    55
Library                                 54
Placements                              54
Fees_and_Account                        48
IT                                      40
Security_and_Safety                     38
Admissions                              34
International_Affair                    32
Name: count, dtype: int64

In [30]:
data[data["intent"]=="Library"]

                                                 query   intent
82   library system not allowing me to reserve book...  Library
112                          What are library timings?  Library
113                             How to reserve a book?  Library
114                           Check book availability?  Library
115                      Library fine payment process?  Library
116                        How to get library no‑dues?  Library
117                            Access online journals?  Library
118                        Plagiarism software access?  Library
119                          Library discipline rules?  Library
120                              Digital books access?  Library
121                          Where is baggage counter?  Library
122                       Lost library book procedure?  Library
123                                Library card issue?  Library
124                    How to extend book return date?  Library
125                               Reading hall timing?  Library
126                      Access newspapers in library?  Library
127                    Library computer center access?  Library
128                      Library resource login issue?  Library
129                            Journal access problem?  Library
130                             Library staff contact?  Library
131                       How to check borrowed books?  Library
296  library card is not working when i try to issu...  Library
338  library book return date not updating in syste...  Library
384        Power supply issue in library basement area  Library
469  i returned library book but fine still showing...  Library
470  cannot access digital library resources from h...  Library
471  library computer login not working when trying...  Library
472  book i reserved online is not showing ready fo...  Library
473  library portal showing error while checking av...  Library
474  library book return not updated in system even...  Library
475  unable to access university e-journal database...  Library
476  library id card not scanning at entry gate ple...  Library
477    book issue machine not working in library today  Library
478     i lost my library card how can i get a new one  Library
479  library fine showing but i already returned th...  Library
480  cannot renew borrowed book through library portal  Library
481  library reading hall seats always full how can...  Library
482  unable to login to digital library portal usin...  Library
483  book i need is showing available but staff sai...  Library
484  library printer not working when trying to pri...  Library
485  digital library page loading very slow please ...  Library
486  library system showing wrong due date for my i...  Library
487  how to request new academic book for library p...  Library
488  unable to access plagiarism software through l...  Library
489  library computer system automatically logging ...  Library
490  book reservation request cancelled automatical...  Library
491  library gate entry not allowing me even with v...  Library
492  cannot open research papers from library database  Library
493  library website showing error while searching ...  Library
494  reading hall light very dim cannot study prope...  Library
495  library staff asked fine but system not showin...  Library
496  book i returned last week still showing issued...  Library
497  unable to download journal article from librar...  Library
498  library study room booking option not working ...  Library

In [31]:
import re
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text

data['query'] = data['query'].apply(preprocess_text)
data.head()

                                          query intent
0  how can i reset my university email password     IT
1           campus wifi is not working properly     IT
2         internet speed is very slow on campus     IT
3                      i forgot my ums password     IT
4             ums portal login error is showing     IT

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [33]:
sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
X_train_embeddings = sbert_model.encode(
    X_train.tolist(),
    show_progress_bar=True
)

X_test_embeddings = sbert_model.encode(
    X_test.tolist(),
    show_progress_bar=True
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

In [34]:
clf = LogisticRegression(max_iter=1000)

clf.fit(X_train_emb, y_train)

LogisticRegression(max_iter=1000)

In [35]:
y_pred = clf.predict(X_test_embeddings)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

Model Accuracy: 0.8482142857142857

Classification Report:

                                      precision    recall  f1-score   support

                           Academics       0.64      0.78      0.70         9
                          Admissions       0.67      0.50      0.57         8
Division_of_Research_and_Development       0.85      0.92      0.88        12
                         Examination       0.62      1.00      0.77         5
                    Fees_and_Account       0.92      0.85      0.88        13
                                  IT       0.83      0.91      0.87        11
                International_Affair       1.00      0.80      0.89         5
                             Library       1.00      0.90      0.95        10
                          Placements       1.00      0.79      0.88        14
                Residential_Services       0.90      0.90      0.90        20
                 Security_and_Safety       0.83      1.00      0.91         5

                            accuracy                           0.85       112
                           macro avg       0.84      0.85      0.84       112
                        weighted avg       0.86      0.85      0.85       112

In [36]:
joblib.dump(clf, "../models/intent_classifier.pkl")

['../models/intent_classifier.pkl']

In [39]:
query = ["my wifi is not working"]

embedding = sbert_model.encode(query)

prediction = clf.predict(embedding)

probabilities = clf.predict_proba(embedding)

print("Predicted intent:", prediction)

print("Probabilities:", probabilities)

Predicted intent: ['IT']
Probabilities: [[0.03657357 0.01631819 0.03383006 0.04144276 0.02139794 0.46380544
  0.02090064 0.06886379 0.05771549 0.20491417 0.03423794]]